"""
these endpoints contain the main application data. they are not included in the
OpenApi documentation, since they contain alot of the boilerplate html & css.

URL's include:
    * GET:
        - /
        - /posts
        - /posts/{post_id}
"""

from typing import Annotated

from fastapi import Depends, Request, status, HTTPException, APIRouter
from sqlalchemy.orm import Session
from sqlalchemy import select

from webapp import models
from webapp.database import get_db
from webapp.main import templates

# NOTE: cant use prefix dueto the "/" home route?!
# router = APIRouter(prefix="/posts")
router = APIRouter()


@router.get("/", name="home", include_in_schema=False)
@router.get("/posts", name="posts", include_in_schema=False)
def home(request: Request, db: Annotated[Session, Depends(get_db)]):
    """
    main url that one sees upon loading up the application
    displays the base.html template

    the 'name' method helps define routes explicitly in case where you have
    multiple decorators

    the "include_in_schema" option means that this url will *NOT* be included
    in the autogenerated documentation pages.
    """
    title: str = "Homepage"
    result = db.execute(select(models.Post))
    posts = result.scalars().all()

    return templates.TemplateResponse(
        request, "home.html", {"posts": posts, "title": title}, 200
    )


@router.get("/posts/{post_id}", include_in_schema=False)
def get_post(post_id: int, request: Request, db: Annotated[Session, Depends(get_db)]):
    """
    return a single post if it exists, otherwise returns appropriate error
    message
    """
    error_message = "Looks like the post does not exist. Try again?"
    result = db.execute(select(models.Post).where(models.Post.id == post_id))
    post = result.scalars().first()

    if not post:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=error_message)

    title: str = post.title[:50]
    return templates.TemplateResponse(
        request, "post.html", {"post": post, "title": title}, 200
    )
