"""
 Copyright (C) 2026 @mbvgua

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

 * main.py - basic fastAPI server to get started building. Contains 3 main 
 endpoints:
    - /
    - /api/posts
    - /api/better-posts
    - /api/way-better-posts

 to run the program:
    $ fastapi dev main.py

 documentation for these routes can be found at: https:127.0.0.1:8000/docs or 
 https:127.0.0.1:8000/redoc once the fastapi server has been started
"""

from fastapi import FastAPI
from fastapi.responses import HTMLResponse

app = FastAPI()


posts: list[dict] = [
    {
        "id": 1,
        "author": "Corey Schafer",
        "title": "FastAPI is Awesome",
        "content": "This framework is really easy to use and super fast.",
        "date_posted": "April 20, 2025",
    },
    {
        "id": 2,
        "author": "Jane Doe",
        "title": "Python is Great for Web Development",
        "content": "Python is a great language for web development, and FastAPI makes it even better.",
        "date_posted": "April 21, 2025",
    },
]


@app.get("/")
def home():
    """
    main url that one sees upon loading up the application. it returns a simple 
    json response saying hello world.
    """
    return {"message":"Hello world!"}


@app.get("/api/posts", include_in_schema=False)
def get_posts():
    """
    slightly advanced url, that returns a list of dictionaries in json format.
    the "include_in_schema" option means that this url will *NOT* be included
    in the autogenerated documentation pages.
    """
    return posts


@app.get("/api/better-posts", response_class=HTMLResponse)
@app.get("/api/way-better-posts", response_class=HTMLResponse)
def get_html_posts():
    """
    returns a list of html posts, but now in html format, allowing the reader
    to easily read them in web-markup. to do this fastAPI relies on the
    HTMLResponse method.
    NOTE: that its possible to stack decorators on the same function, meaning
    that both routes used above will lead to the same page.
    """
    try:
        if len(posts) > 0:
            for post in posts:
                # FIXME: only gives one item, not the whole list of items?
                page = f"""
                <h1 id="{post['id']}"> {post['title']} </h1>
                <p> {post['content']} </p>
                <p> by {post['author']} on {post['date_posted']} </p>
                """
                return page

    except Exception as e:
        error:str = f"Oops! An error occurred: {e}"
        return error
