"""
Copyright (C) 2026 <@mbvgua>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* main.py - basic fastAPI server to get started building. Contains the
following URL endpoints:
   - /
   - /posts
   - /posts/{post_id}
   - /api/posts
   - /api/posts/{post_id}

to run the program:
   $ fastapi dev main.py

once the server has been started, api documentation can be found at:
    - https:127.0.0.1:8000/docs
    - https:127.0.0.1:8000/redoc
"""

from fastapi import FastAPI, Request, status, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.status import HTTP_201_CREATED

from validators import PostCreate, PostResponse

app = FastAPI()
# load css & html
app.mount("/static", StaticFiles(directory="static"), name="static")
templates: Jinja2Templates = Jinja2Templates(directory="templates")

posts: list[dict] = [
    {
        "id": 1,
        "author": "Corey Schafer",
        "title": "FastAPI is Awesome",
        "content": "This framework is really easy to use and super fast.",
        "date_posted": "April 20, 2025",
    },
    {
        "id": 2,
        "author": "Jane Doe",
        "title": "Python is Great for Web Development",
        "content": "Python is a great language for web development, and FastAPI makes it even better.",
        "date_posted": "April 21, 2025",
    },
]


@app.get("/", name="home", include_in_schema=False)
@app.get("/posts", name="posts", include_in_schema=False)
def home(request: Request):
    """
    main url that one sees upon loading up the application
    displays the base.html template

    the 'name' method helps define routes explicitly in case where you have
    multiple decorators

    the "include_in_schema" option means that this url will *NOT* be included
    in the autogenerated documentation pages.
    """
    title: str = "Homepage"
    return templates.TemplateResponse(
        request, "home.html", {"posts": posts, "title": title}, 200
    )


@app.get("/posts/{post_id}", include_in_schema=False)
def get_post(post_id: int, request: Request):
    """
    return a single post if it exists, otherwise returns appropriate error
    message
    """
    error_message = "Looks like the post does not exist. Try again?"
    for post in posts:
        if post.get("id") == post_id:
            title: str = f"Post-{post_id}"
            return templates.TemplateResponse(
                request, "post.html", {"post": post, "title": title}, 200
            )

    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=error_message)


# API JSON Responses
@app.post("/api/posts/", response_model=PostResponse, status_code=HTTP_201_CREATED)
def create_post(post: PostCreate):
    """
    endpoint for creating posts in JSON format
    """
    # create new post id, appending by 1 to the existing, else makeit 1
    new_id = max(post["id"] for post in posts) + 1 if posts else 1

    new_post = {
        "id": new_id,
        "author": post.author,
        "title": post.title,
        "content": post.content,
        "date_posted": "January 01,2025",
    }
    posts.append(new_post)
    return new_post


@app.get("/api/posts/", response_model=list[PostResponse])
def get_posts_api():
    """
    API endpoint to return all posts within the application in JSON format
    """
    return posts


@app.get("/api/posts/{post_id}")
def get_post_api(post_id: int, response_model=PostResponse):
    """
    return specific post by narrowing down with its ID
    """
    error_message = "Oops! Looks like the post does not exist. Try again?"
    for post in posts:
        if post.get("id") == post_id:
            return post

    return {"error": error_message}


# Exception Handling
@app.exception_handler(StarletteHTTPException)
def general_http_exception_handler(request: Request, exception: StarletteHTTPException):
    """
    use exception handler to catch any StarletteHTTPException's raised via code
    execution.

    fastapi is built on top of starlette, hence why its execptions are also imported
    alongside those of fastapi, lest some will be missed.
    """
    message = exception.detail if exception.detail else "An error occurred, try again?"

    # if url starts with "/api/..." return JSON response
    if request.url.path.startswith("/api"):
        return JSONResponse(
            status_code=exception.status_code, content={"detail": message}
        )
    # else return 'error.html' template
    else:
        return templates.TemplateResponse(
            request,
            "error.html",
            {
                "status_code": exception.status_code,
                "title": exception.status_code,
                "message": message,
            },
            status_code=exception.status_code,
        )


# Validation Error Handling
@app.exception_handler(RequestValidationError)
def validation_exception_handler(request: Request, exception: RequestValidationError):
    """
    hanlde validation errors
    """
    message = "An error occurred, try again?"

    # if url starts with "/api/..." return JSON response
    if request.url.path.startswith("/api"):
        return JSONResponse(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            content={"detail": exception.errors()},
        )
    # else return 'error.html' template
    else:
        return templates.TemplateResponse(
            request,
            "error.html",
            {
                "status_code": status.HTTP_422_UNPROCESSABLE_CONTENT,
                "title": status.HTTP_422_UNPROCESSABLE_CONTENT,
                "message": message,
            },
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
        )
