"""
Copyright (C) 2026 <@mbvgua>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* main.py - basic fastAPI server to get started building. Contains the
following URL endpoints:
   - /
   - /api/posts

to run the program:
   $ fastapi dev main.py

documentation for these routes can be found at: https:127.0.0.1:8000/docs or
https:127.0.0.1:8000/redoc once the fastapi server has been started
"""

from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

app = FastAPI()
# load css & html
app.mount("/static", StaticFiles(directory="static"), name="static")
templates: Jinja2Templates = Jinja2Templates(directory="templates")

posts: list[dict] = [
    {
        "id": 1,
        "author": "Corey Schafer",
        "title": "FastAPI is Awesome",
        "content": "This framework is really easy to use and super fast.",
        "date_posted": "April 20, 2025",
    },
    {
        "id": 2,
        "author": "Jane Doe",
        "title": "Python is Great for Web Development",
        "content": "Python is a great language for web development, and FastAPI makes it even better.",
        "date_posted": "April 21, 2025",
    },
]


@app.get("/", name="home", include_in_schema=False)
@app.get("/posts", name="posts", include_in_schema=False)
def home(request: Request):
    """
    main url that one sees upon loading up the application
    displays the base.html template

    the 'name' method helps define routes explicitly in case where you have
    multiple decorators

    the "include_in_schema" option means that this url will *NOT* be included
    in the autogenerated documentation pages.
    """
    title: str = "Homepage"
    return templates.TemplateResponse(
        request, "home.html", {"posts": posts, "title": title}, 200
    )


@app.get("/api/posts")
def get_posts():
    """
    this url returns a list of posts in json format.
    """
    return posts
