"""
pydantic schemas help prevent exposing data that should not bee seen by all.
it also helps validate schemas, preventing api access until all required fields
are inputted.

below are validation schemas for the posts model. they include:
    - PostBase
    - PostCreate
    - PostResponse

these schemas are enforced by fastapi and generated automaticaly in the docs
"""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from webapp.schemas.users import UserResponse


class PostBase(BaseModel):
    """
    the main base schema. this conatins data fields that are shared between
    the PostCreate and PostResponse schemas.
    """

    title: str = Field(min_length=5, max_length=50)
    content: str = Field(min_length=10)


class PostCreate(PostBase):
    """
    inherits from PostBase schema. add a 'user_id' field which is essenetial
    for anyone creating a new post. helps ensure they are in they are already
    in the system
    """

    user_id: int  # HACK: before adding auth


class PostResponse(PostBase):
    """
    inherits from PostBase schema. adds the following schemas:
        - id
        - user_id
        - date_posted: auto-generated by the system
    """

    model_config = ConfigDict(from_attributes=True)  # allow using dot-notation

    id: int
    user_id: int
    date_posted: datetime
    author: UserResponse
