"""
pydantic schemas help prevent exposing data that should not bee seen by all.
it also helps validate schemas, preventing api access until all required fields
are inputted.

below are validation schemas for the posts model. they include:
    - PostBase
    - PostCreate
    - PostResponse

these schemas are enforced by fastapi and generated automaticaly in the docs
"""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from webapp.schemas.users import UserResponse


# validation schemas for Posts
class PostBase(BaseModel):
    """
    schema for data fields shared between the PostCreate & PostResponse schemas
    """

    title: str = Field(min_length=5, max_length=50)
    content: str = Field(min_length=10)


class PostCreate(PostBase):
    """
    inherits from PostBase above
    """

    user_id: int  # HACK: before adding auth


class PostResponse(PostBase):
    """
    inherits from PostBase

    adds 'id','user_id' & 'date_posted' which are auto-generated by the system and not
    inputted by the user
    """

    model_config = ConfigDict(from_attributes=True)  # allow using dot-notation

    id: int
    user_id: int
    date_posted: datetime
    author: UserResponse
