"""
pydantic schemas help prevent exposing data that should not bee seen by all.
it also helps validate schemas, preventing api access until all required fields
are inputted.

below are validation schemas for the posts model. they include:
    - PostBase
    - PostCreate
    - PostResponse
    - PaginatedPostResponse

these schemas are enforced by fastapi and generated automaticaly in the docs
"""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.users import UserPublicResponse


class PostBase(BaseModel):
    """
    the main base schema. this conatins data fields that are shared between
    the PostCreate and PostResponse schemas.
    """

    title: str = Field(min_length=5, max_length=100)
    content: str = Field(min_length=10)


class PostCreate(PostBase):
    """
    inherits from PostBase schema. the user_id will now be determined from the
    user token passed in, hence one cannot claim to be someone they're not
    """

    pass


class PostResponse(PostBase):
    """
    inherits from PostBase schema. adds the following schemas:
        - id
        - user_id
        - date_posted: auto-generated by the system
    """

    model_config = ConfigDict(from_attributes=True)  # allow using dot-notation

    id: int
    user_id: int
    date_posted: datetime
    author: UserPublicResponse


class PostUpdate(BaseModel):
    """
    inherits from the BaseModel, since its an update, it makes all fields
    optional. If it were to inherit from the PostBase schema, it would mean
    overwriting them, which causes errors.

    NOTE:
    - since the inputs are optional, they have to have a 'default' value
    - we do not include the 'id' value for update as that would change
      ownership of the posts
    """

    title: str | None = Field(default=None, min_length=5, max_length=50)
    content: str | None = Field(default=None, min_length=10)

class PaginatedPostResponse(BaseModel):
    """
    inherits from the BaseModel. it returns data essential for making the post
    list page paginated, returning data sequentially.
    """

    posts: list[PostResponse]
    total: int
    skip: int
    limit: int
    has_more: bool
