"""
contains routes for the /posts endpoints. these are not included in the
documentation docs, since they return formatted output(boilerplate html & css)

endpoints included here are:
    * CREATE:
    * READ(GET):
        - /posts
        - /posts/{post_id}
    * UPDATE:
    * DELETE:
"""

from typing import Annotated

from fastapi import Depends, Request, status, HTTPException, APIRouter
from sqlalchemy.orm import Session
from sqlalchemy import select

from webapp import models
from webapp.database import get_db
from webapp.main import templates

router = APIRouter(prefix="/posts")


@router.get("/", include_in_schema=False)
def get_posts(request: Request, db: Annotated[Session, Depends(get_db)]):
    """
    main url that appears upon loading the application. it returns all the posts
    currently present in the database, formatted in the 'home.html' template

    NOTE:
    - 'include_in_schema': set whether or not this url will be included in the
      autogenerated documentation pages
    """

    title: str = "Homepage"
    data = db.execute(select(models.Post))
    posts = data.scalars().all()

    return templates.TemplateResponse(
        request, "home.html", {"posts": posts, "title": title}, 200
    )


@router.get("/{post_id}", include_in_schema=False)
def get_post_by_id(
    post_id: int, request: Request, db: Annotated[Session, Depends(get_db)]
):
    """
    returns a single post, based on the 'post_id' passed in as a parameter.
    if no such post exists, it returns appropriate error message
    """

    data = db.execute(select(models.Post).where(models.Post.id == post_id))
    post = data.scalars().first()

    # fail first, fail visibly
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Looks like the post does not exist. Try again?",
        )

    title: str = post.title[:50]
    return templates.TemplateResponse(
        request, "post.html", {"post": post, "title": title}, 200
    )
