"""
contains routes for the "/posts" endpoints.

these routes will not be included in the documentation docs, as since they
return formatted output in html & css.

endpoints included here are:
    * CREATE:
    * READ(GET):
        - /posts: get_posts
        - /posts/{post_id}: get_post_by_id
    * UPDATE:
    * DELETE:

the Create, Update and Delete endpoints not created here are facilated through
the frontend, whereby the it hooks the bootstrap UI via modals to the needed
backend API in "/api/posts" and performs the needed operations
"""

from typing import Annotated

from fastapi import Depends, Request, status, HTTPException, APIRouter
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
from sqlalchemy import select

from webapp.database import models
from webapp.database.config import get_db
from webapp.main import templates

router = APIRouter(prefix="/posts", tags=["post views"])


@router.get("", include_in_schema=False)
async def get_posts(request: Request, db: Annotated[AsyncSession, Depends(get_db)]):
    """
    main url that appears upon loading the application. it returns all the posts
    currently present in the database, formatted using html % css in the
    'templates/home.html' template

    NOTE:
    - 'include_in_schema': set whether or not this url will be included in the
      autogenerated documentation pages. False means it wont be included
    - 'selectinload': in synchronous SQLAlchemy, lazy loading just works. for
      the 'Post' object, SQLAlchemy automatically runs a query to load
      'Post.author' when you try to access it, hence templates are able to
      acces 'post.author.username' with no issues. for async SQLAlchemy, lazy
      loading is not supported hence the above will result in errors; this is
      fixed by eagerly loading! 'selectinload' enables this by telling
      SQLAlchemy to load things immediately alongside the main query.
    """

    title: str = "Homepage"
    data = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))
        .order_by(models.Post.date_posted.desc())
    )
    posts = data.scalars().all()

    return templates.TemplateResponse(
        request, "home.html", {"posts": posts, "title": title}, status.HTTP_200_OK
    )


@router.get("/{post_id}", include_in_schema=False)
async def get_post_by_id(
    post_id: int, request: Request, db: Annotated[AsyncSession, Depends(get_db)]
):
    """
    returns a single post template formatted in the "templates/post.html"
    template, based on the 'post_id' passed in as a parameter.
    if no such post exists, it returns appropriate error message

    NOTE:
    - "selectinload()": allows for eargely loading in the async sqlite session,
      hence the request is able to access "models.Post.author", lest it would
      return and error
    """

    data = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))
        .where(models.Post.id == post_id)
    )
    post = data.scalars().first()

    # fail first, fail visibly
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Oh no! It looks like the post does not exist. Try again?",
        )

    title: str = post.title[:50]
    return templates.TemplateResponse(
        request, "post.html", {"post": post, "title": title}, status.HTTP_200_OK
    )
