"""
contains routes for the /posts endpoints. these are not included in the
documentation docs, since they return formatted output(boilerplate html & css)

endpoints included here are:
    * CREATE:
    * READ(GET):
        - /posts
        - /posts/{post_id}
    * UPDATE:
    * DELETE:
"""

from typing import Annotated

from fastapi import Depends, Request, status, HTTPException, APIRouter
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
from sqlalchemy import select

from webapp.database import models
from webapp.database.config import get_db
from webapp.main import templates

router = APIRouter(prefix="/posts")


@router.get("/", include_in_schema=False)
async def get_posts(request: Request, db: Annotated[AsyncSession, Depends(get_db)]):
    """
    main url that appears upon loading the application. it returns all the posts
    currently present in the database, formatted in the 'home.html' template

    NOTE:
    - 'include_in_schema': set whether or not this url will be included in the
      autogenerated documentation pages
    - 'selectinload': in synchronous SQLAlchemy, lazy loading just works. for
      the 'Post' object, SQLAlchemy automatically runs a query to load
      'Post.author' when you try to access it, hence templates are able to
      acces 'post.author.username' with no issues. for async SQLAlchemy, lazy
      loading is not supported hence the above will result in errors; this is
      fixed by eagerly loading! 'selectinload' enables this by telling
      SQLAlchemy to load things immediately alongside the main query.
    """

    title: str = "Homepage"
    data = await db.execute(
        select(models.Post).options(selectinload(models.Post.author))
    )
    posts = data.scalars().all()

    return templates.TemplateResponse(
        request, "home.html", {"posts": posts, "title": title}, 200
    )


@router.get("/{post_id}", include_in_schema=False)
async def get_post_by_id(
    post_id: int, request: Request, db: Annotated[AsyncSession, Depends(get_db)]
):
    """
    returns a single post, based on the 'post_id' passed in as a parameter.
    if no such post exists, it returns appropriate error message
    """

    data = await db.execute(
        select(models.Post)
        .options(selectinload(models.Post.author))
        .where(models.Post.id == post_id)
    )
    post = data.scalars().first()

    # fail first, fail visibly
    if not post:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Looks like the post does not exist. Try again?",
        )

    title: str = post.title[:50]
    return templates.TemplateResponse(
        request, "post.html", {"post": post, "title": title}, 200
    )
