"""
these endpoints contain the main application data. they are not included in the
OpenApi documentation, since they contain alot of the boilerplate html & css.

URL's include:
    * GET:
        - /
        - /posts
        - /posts/{post_id}
"""
from fastapi import Request, status, HTTPException, APIRouter

from . import templates, posts

router = APIRouter()


@router.get("/", name="home", include_in_schema=False)
@router.get("/posts", name="posts", include_in_schema=False)
def home(request: Request):
    """
    main url that one sees upon loading up the application
    displays the base.html template

    the 'name' method helps define routes explicitly in case where you have
    multiple decorators

    the "include_in_schema" option means that this url will *NOT* be included
    in the autogenerated documentation pages.
    """
    title: str = "Homepage"
    return templates.TemplateResponse(
        request, "home.html", {"posts": posts, "title": title}, 200
    )


@router.get("/posts/{post_id}", include_in_schema=False)
def get_post(post_id: int, request: Request):
    """
    return a single post if it exists, otherwise returns appropriate error
    message
    """
    error_message = "Looks like the post does not exist. Try again?"
    for post in posts:
        if post.get("id") == post_id:
            title: str = f"Post-{post_id}"
            return templates.TemplateResponse(
                request, "post.html", {"post": post, "title": title}, 200
            )

    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=error_message)
