"""
pydantic schemas help prevent exposing data that should not bee seen by all.
it also helps validate schemas, preventing api access until all required fields
are inputted.

these schemas are enforced by fastapi and generated automaticaly in the docs
"""
from pydantic import BaseModel, ConfigDict, Field


class PostBase(BaseModel):
    author: str = Field(min_length=5, max_length=50)
    title: str = Field(min_length=5, max_length=50)
    content: str = Field(min_length=10)


class PostCreate(PostBase):
    """
    inherits from PostBase above
    """

    pass


class PostResponse(PostBase):
    """
    also inherits from PostBase, but adds in id & date_posted
    these two are auto-generated by system and not given by user
    """

    model_config = ConfigDict(from_attributes=True)  # allow using dot-notation

    id: int
    date_posted: str
